
source ~/.zshrc.common

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home1/08203/ywchoi92/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home1/08203/ywchoi92/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home1/08203/ywchoi92/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home1/08203/ywchoi92/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

conda activate local

module load python3

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

