
# zsh theme (pure)
fpath+=("$(brew --prefix)/share/zsh/site-functions")
autoload -U promptinit; promptinit
prompt pure

# basic setup
export EDITOR=nvim
export PATH=${HOME}/local/bin:${PATH}

set -o autopushd
bindkey -v

alias ls='ls -G'
alias l='ls -l'
alias lsr='ls -l --sort=date'
alias python=python3
alias py=python3
alias vi=nvim
alias vim=nvim

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# zoxide
eval "$(zoxide init zsh)"
