
# zsh theme (pure)
fpath+=("$(brew --prefix)/share/zsh/site-functions")
autoload -U promptinit; promptinit
prompt pure

# basic setup
export EDITOR=nvim
export PATH=${HOME}/local/bin:${PATH}

set -o autopushd
bindkey -v

alias ls='ls --color=auto'
alias l='ls -l'
alias lsr='ls -l --sort=date'
alias python=python3
alias py=python3
alias vi=nvim
alias vim=nvim
alias gs="git status"

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export FZF_COMPLETION_TRIGGER='@'
zle     -N             fzf-cd-widget
bindkey -M emacs '^g' fzf-cd-widget
bindkey -M vicmd '^g' fzf-cd-widget
bindkey -M viins '^g' fzf-cd-widget


# zoxide
eval "$(zoxide init zsh)"


test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

