
source ~/.zshrc.common

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# module restore default
module load python3 pdf5 >& /dev/null
alias qs=sqs

export PATH=${WORK}/local/bin:${PATH}
export LD_LIBRARY_PATH=${WORK}/local/lib:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH=${WORK}/local/lib64:${LD_LIBRARY_PATH}

export PATH=${HOME}/.local/bin:${PATH}

alias work="cd ${WORK}/Workspace"
cd-to-workspace() {
  zle push-line # Clear buffer. Auto-restored on next prompt.
  BUFFER="cd ${WORK}/Workspace"
  zle accept-line
  local ret=$?
  unset dir # ensure this doesn't end up appearing in prompt expansion
  zle reset-prompt
  return $ret
}
zle     -N   cd-to-workspace
bindkey '^W' cd-to-workspace

alias co=code

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

alias python=python3
alias py=python

export EDITOR=nvim
alias vi=nvim
alias vim=nvim

export SIESTA=${WORK}/Codes/siesta/4.1.5/Obj/siesta
export QEBIN=${WORK}/Codes/qe/6.8/bin
# export GITSTATUS_LOG_LEVEL=DEBUG

export NODE_OPTIONS=--max_old_space_size=4096
alias ls='/bin/ls --color=always'

mkcase() {
  if mkdir $@; then
    local dirname="${@: -1}"
    echo "*" >> ${dirname}/.gitignore
    echo "!.gitignore" >> ${dirname}/.gitignore
  fi
}
