
source ~/.zshrc.common

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# module restore default
module load python3 phdf5 >& /dev/null
alias qs=sqs

export WORK=/work/08203/ywchoi92/frontera

export PATH=${WORK}/local/bin:${PATH}
export LD_LIBRARY_PATH=${WORK}/local/lib:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH=${WORK}/local/lib64:${LD_LIBRARY_PATH}

export PATH=${HOME}/.local/bin:${PATH}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

alias python=python3
alias py=python

export EDITOR=nvim

alias vi=nvim
alias vim=nvim

# export PATH=${WORK}/Codes/siesta/psml-support/Obj:${PATH}
export PATH=${WORK}/Codes/siesta/4.1.5/Obj-CLX:${PATH}
export PATH=${HOME}/qe-7.1/bin:${PATH}
# export GITSTATUS_LOG_LEVEL=DEBUG

alias ls='/bin/ls --color=always'

export CC=icc
export FC=ifort
