
source ~/.zshrc.common

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

module load impi python/3.8-anaconda-2020.11

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/usr/common/software/python/3.8-anaconda-2020.11/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/usr/common/software/python/3.8-anaconda-2020.11/etc/profile.d/conda.sh" ]; then
        . "/usr/common/software/python/3.8-anaconda-2020.11/etc/profile.d/conda.sh"
    else
        export PATH="/usr/common/software/python/3.8-anaconda-2020.11/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

conda activate local

alias work="cd ${SCRATCH}"
cd-to-workspace() {
  zle push-line # Clear buffer. Auto-restored on next prompt.
  BUFFER="cd ${SCRATCH}"
  zle accept-line
  local ret=$?
  unset dir # ensure this doesn't end up appearing in prompt expansion
  zle reset-prompt
  return $ret
}
zle     -N   cd-to-workspace
bindkey '^W' cd-to-workspace

export PYTHONPATH="/global/homes/y/ywchoi/.local/cori/3.8-anaconda-2020.11/lib:${PYTHONPATH}"
export JUPYTER_PATH="/global/homes/y/ywchoi/.local/cori/3.8-anaconda-2020.11/lib:${JUPYTER_PATH}"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


alias qs=sqs
alias qi='sinfo --format="%15b %8D %A"'
