
# source ~/.zshrc.common

# test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# alias qs=sqs

# alias ls='ls --color=auto'
# alias vi=nvim
# alias vim=nvim
